---
title: "Classification of Functional Outcoes with Linear Optimal Low Rank Projection (LOL)"
author: "Shubhayu Bhattacharyay, Eshan Joshi, and Matthew Wang"
date: "4/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(devtools)
if (!require(lolR)) install_github('neurodata/lol', build_vignettes=TRUE, force=TRUE)
library(lolR)
library(R.matlab)
library(tidyverse)
library(ggplot2)
library(plotly)
library(naniar)
library(MASS)
library(caret)
library(cvAUC)
library(precrec)
library(plotfunctions)
source("../functions/generateRootDir.R")
```

## Classification Scheme:
### Predictors:
* Age
* APACHE (for mortality prediction)
* GCS_en (for GOSE prediction)
* Motion Features (3 dimensions)

### Outcomes:
* 1: GOSE at Discharge
* 2: GOSE at 1 year
* 3: Mortality during hospital stay
* 4: Mortality within 1 year


```{r }
get_auc_info <- function(list_of_preds){
  
return (lapply(c(2:14), function(y) {
          lapply(seq_along(list_of_preds[[1]]), function(x) {
            cvAUC(list(list_of_preds[[1]][[x]][[y]],
                       list_of_preds[[2]][[x]][[y]],
                       list_of_preds[[3]][[x]][[y]],
                       list_of_preds[[4]][[x]][[y]],
                       list_of_preds[[5]][[x]][[y]]),
                  list(list_of_preds[[1]][[x]]$ground_truth,
                       list_of_preds[[2]][[x]]$ground_truth,
                       list_of_preds[[3]][[x]]$ground_truth,
                       list_of_preds[[4]][[x]]$ground_truth,
                       list_of_preds[[5]][[x]]$ground_truth))})
          }))
}

get_precrec_info <- function(list_of_preds){
  
return (lapply(c(2:14), function(y) {
          lapply(seq_along(list_of_preds[[1]]), function(x) {
            s<-join_scores(list_of_preds[[1]][[x]][y],
                           list_of_preds[[2]][[x]][y],
                           list_of_preds[[3]][[x]][y],
                           list_of_preds[[4]][[x]][y],
                           list_of_preds[[5]][[x]][y], chklen = FALSE)
            l<-join_labels(list_of_preds[[1]][[x]][1],
                           list_of_preds[[2]][[x]][1],
                           list_of_preds[[3]][[x]][1],
                           list_of_preds[[4]][[x]][1],
                           list_of_preds[[5]][[x]][1], chklen = FALSE)            
            evalmod(scores=s,labels=l, dsids=1:5)})
}))
}

## [[1]]:bp_pred [[2]]:fe_pred [[3]]:fp_pred [[4]]:mf_pred [[5]]:sm_pred [[6]]:wv_pred
get_auc_plots <- function(plot_info, auc_info){
  filePath = paste0("../",generateRootDir(paste0(deparse(substitute(plot_info)),"/")))
  dir.create(filePath, recursive=TRUE,showWarnings = FALSE)
  color_choice = factor(auc_info[[1]][[1]])[2:14]
  names(color_choice) = gsub("_X1","",names(color_choice))
  col_vector<-palette(c(rgb(0,184,172, maxColorValue=255),
                        rgb(122,0,140, maxColorValue=255),
                        rgb(181,255,74, maxColorValue=255),
                        rgb(248,137,255, maxColorValue=255),
                        rgb(0,106,57, maxColorValue=255),
                        rgb(175,0,71, maxColorValue=255),
                        rgb(247,255,171, maxColorValue=255),
                        rgb(2,98,202, maxColorValue=255),
                        rgb(255,196,89, maxColorValue=255),
                        rgb(27,0,25, maxColorValue=255),
                        rgb(157,129,0, maxColorValue=255),
                        rgb(157,216,255, maxColorValue=255),
                        rgb(255,208,234, maxColorValue=255)))
  val<-names(auc_info[[1]])
  lapply(c(1:6), function(y) {
    tiff(paste0(filePath,val[y],".tiff"))
      lapply(seq_along(plot_info), function(x) {
      plot(plot_info[[x]][[y]]$perf, col="grey", lty=3)
      plot(plot_info[[x]][[y]]$perf, avg="vertical",col=col_vector[x], lwd=2, add=TRUE) 
      # plot_error(rowMeans(sapply(plot_info[[x]][[y]]$perf@x.values, `length<-`, max(lengths(plot_info[[x]][[y]]$perf@x.values))), 
      #                     na.rm=TRUE),rowMeans(sapply(plot_info[[x]][[y]]$perf@y.values, `length<-`, 
      #                                                 max(lengths(plot_info[[x]][[y]]$perf@y.values))), na.rm=TRUE),type="n", 
      #            se.fit=sd(plot_info[[x]][[y]]$fold.AUC), shade=TRUE, col="grey",alpha=0.10)
      par(new=TRUE) 
      })
    legend("bottomright", legend=names(color_choice),fill=col_vector,cex=0.75)  
    title(val[y])
    dev.off()
  })
}     

get_precrec_plots <- function(plot_info, auc_info){
  filePath = paste0("../",generateRootDir(paste0(gsub("_pr","",deparse(substitute(plot_info))),"/")))
  color_choice = factor(auc_info[[1]][[1]])[2:14]
  names(color_choice) = gsub("_X1","",names(color_choice))
  col_vector<-palette(c(rgb(0,184,172, maxColorValue=255),
                        rgb(122,0,140, maxColorValue=255),
                        rgb(181,255,74, maxColorValue=255),
                        rgb(248,137,255, maxColorValue=255),
                        rgb(0,106,57, maxColorValue=255),
                        rgb(175,0,71, maxColorValue=255),
                        rgb(247,255,171, maxColorValue=255),
                        rgb(2,98,202, maxColorValue=255),
                        rgb(255,196,89, maxColorValue=255),
                        rgb(27,0,25, maxColorValue=255),
                        rgb(157,129,0, maxColorValue=255),
                        rgb(157,216,255, maxColorValue=255),
                        rgb(255,208,234, maxColorValue=255)))  
  val<-names(auc_info[[1]])
    for (i in 1:6){
      png(paste0(filePath,val[i],"_prc.png"))
      p_roc <<- ggplot()
      for (j in 1:13){
        p_roc <<- p_roc + geom_line(data=cbind(motion_feats=col_vector[j],subset(fortify(plot_info[[j]][[i]]), curvetype == "PRC")),
                                   mapping=aes(x = x, y = y, color = motion_feats))
      }
      p_roc <<- p_roc + xlab("Recall") + ylab("Precision") + ggtitle(val[i])+  
        theme(text=element_text(size=18),axis.text.x=element_text(angle=50,hjust=1),panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),plot.title = element_text(hjust = 0.5))
      print(p_roc)
      dev.off()
    }
}

#lapply(c(1:5), function(x) calibration(ground_truth~bp_clin_glm,data=self_val_GLM_predictionsDis[[x]][[1]]))
```

```{r echo=FALSE}
self_GLM_dis<-get_auc_info(self_val_GLM_predictionsDis)
get_auc_plots(self_GLM_dis,self_val_GLM_predictionsDis)
self_GLM_dis_pr<-get_precrec_info(self_val_GLM_predictionsDis)
get_precrec_plots(self_GLM_dis_pr,self_val_GLM_predictionsDis)
self_GLM_12mo<-get_auc_info(self_val_GLM_predictions12mo)
get_auc_plots(self_GLM_12mo,self_val_GLM_predictions12mo)
self_GLM_12mo_pr<-get_precrec_info(self_val_GLM_predictions12mo)
get_precrec_plots(self_GLM_12mo_pr,self_val_GLM_predictions12mo)

test_GLM_dis<-get_auc_info(test_val_GLM_predictionsDis)
get_auc_plots(test_GLM_dis,test_val_GLM_predictionsDis)
test_GLM_dis_pr<-get_precrec_info(test_val_GLM_predictionsDis)
get_precrec_plots(test_GLM_dis_pr,test_val_GLM_predictionsDis)
test_GLM_12mo<-get_auc_info(test_val_GLM_predictions12mo)
get_auc_plots(test_GLM_12mo,test_val_GLM_predictions12mo)
test_GLM_12mo_pr<-get_precrec_info(test_val_GLM_predictions12mo)
get_precrec_plots(test_GLM_12mo_pr,test_val_GLM_predictions12mo)

self_SVM_dis<-get_auc_info(self_val_SVM_predictionsDis)
get_auc_plots(self_SVM_dis,self_val_SVM_predictionsDis)
self_SVM_dis_pr<-get_precrec_info(self_val_SVM_predictionsDis)
get_precrec_plots(self_SVM_dis_pr,self_val_SVM_predictionsDis)
self_SVM_12mo<-get_auc_info(self_val_SVM_predictions12mo)
get_auc_plots(self_SVM_12mo,self_val_SVM_predictions12mo)
self_SVM_12mo_pr<-get_precrec_info(self_val_SVM_predictions12mo)
get_precrec_plots(self_SVM_12mo_pr,self_val_SVM_predictions12mo)

test_SVM_dis<-get_auc_info(test_val_SVM_predictionsDis)
get_auc_plots(test_SVM_dis,test_val_SVM_predictionsDis)
test_SVM_dis_pr<-get_precrec_info(test_val_SVM_predictionsDis)
get_precrec_plots(test_SVM_dis_pr,test_val_SVM_predictionsDis)
test_SVM_12mo<-get_auc_info(test_val_SVM_predictions12mo)
get_auc_plots(test_SVM_12mo,test_val_SVM_predictions12mo)
test_SVM_12mo_pr<-get_precrec_info(test_val_SVM_predictions12mo)
get_precrec_plots(test_SVM_12mo_pr,test_val_SVM_predictions12mo)

self_LDA_dis<-get_auc_info(self_val_LDA_predictionsDis)
get_auc_plots(self_LDA_dis,self_val_LDA_predictionsDis)
self_LDA_dis_pr<-get_precrec_info(self_val_LDA_predictionsDis)
get_precrec_plots(self_LDA_dis_pr,self_val_LDA_predictionsDis)
self_LDA_12mo<-get_auc_info(self_val_LDA_predictions12mo)
get_auc_plots(self_LDA_12mo,self_val_LDA_predictions12mo)
self_LDA_12mo_pr<-get_precrec_info(self_val_LDA_predictions12mo)
get_precrec_plots(self_LDA_12mo_pr,self_val_LDA_predictions12mo)

test_LDA_dis<-get_auc_info(test_val_LDA_predictionsDis)
get_auc_plots(test_LDA_dis,test_val_LDA_predictionsDis)
test_LDA_dis_pr<-get_precrec_info(test_val_LDA_predictionsDis)
get_precrec_plots(test_LDA_dis_pr,test_val_LDA_predictionsDis)
test_LDA_12mo<-get_auc_info(test_val_LDA_predictions12mo)
get_auc_plots(test_LDA_12mo,test_val_LDA_predictions12mo)
test_LDA_12mo_pr<-get_precrec_info(test_val_LDA_predictions12mo)
get_precrec_plots(test_LDA_12mo_pr,test_val_LDA_predictions12mo)

self_kNN_dis<-get_auc_info(self_val_kNN_predictionsDis)
get_auc_plots(self_kNN_dis,self_val_kNN_predictionsDis)
self_kNN_dis_pr<-get_precrec_info(self_val_kNN_predictionsDis)
get_precrec_plots(self_kNN_dis_pr,self_val_kNN_predictionsDis)
self_kNN_12mo<-get_auc_info(self_val_kNN_predictions12mo)
get_auc_plots(self_kNN_12mo,self_val_kNN_predictions12mo)
self_kNN_12mo_pr<-get_precrec_info(self_val_kNN_predictions12mo)
get_precrec_plots(self_kNN_12mo_pr,self_val_kNN_predictions12mo)

test_kNN_dis<-get_auc_info(test_val_kNN_predictionsDis)
get_auc_plots(test_kNN_dis,test_val_kNN_predictionsDis)
test_kNN_dis_pr<-get_precrec_info(test_val_kNN_predictionsDis)
get_precrec_plots(test_kNN_dis_pr,test_val_kNN_predictionsDis)
test_kNN_12mo<-get_auc_info(test_val_kNN_predictions12mo)
get_auc_plots(test_kNN_12mo,test_val_kNN_predictions12mo)
test_kNN_12mo_pr<-get_precrec_info(test_val_kNN_predictions12mo)
get_precrec_plots(test_kNN_12mo_pr,test_val_kNN_predictions12mo)
```

```{r }
get_auc_mean_sd <- function(plot_info, auc_info){
  filePath = paste0("../",generateRootDir(paste0(deparse(substitute(plot_info)))))
  info_list<-list()
  lapply(c(1:6), function(y) {
      means <- c()
      stddevs <- c()
      lapply(seq_along(plot_info), function(x) {
      means<<-c(means,mean(plot_info[[x]][[y]]$fold.AUC))
      stddevs<<-c(stddevs,sd(plot_info[[x]][[y]]$fold.AUC))
      })
      info_list[[y]]<<-data.frame(mean=means,stddev=stddevs, row.names=gsub(".X1","",names(auc_info[[1]][[1]])[2:14]))
  })
  names(info_list)<-c(names(auc_info[[1]]))
  write.csv(info_list, file = paste0(filePath,".csv"),
            row.names = TRUE)
}
```

```{r }
get_auc_mean_sd(self_GLM_dis,self_val_GLM_predictionsDis)
get_auc_mean_sd(self_GLM_12mo,self_val_GLM_predictions12mo)
get_auc_mean_sd(test_GLM_dis,test_val_GLM_predictionsDis)
get_auc_mean_sd(test_GLM_12mo,test_val_GLM_predictions12mo)
# 
get_auc_mean_sd(self_SVM_dis,self_val_SVM_predictionsDis)
get_auc_mean_sd(self_SVM_12mo,self_val_SVM_predictions12mo)
get_auc_mean_sd(test_SVM_dis,test_val_SVM_predictionsDis)
get_auc_mean_sd(test_SVM_12mo,test_val_SVM_predictions12mo)
# 
get_auc_mean_sd(self_LDA_dis,self_val_LDA_predictionsDis)
get_auc_mean_sd(self_LDA_12mo,self_val_LDA_predictions12mo)
get_auc_mean_sd(test_LDA_dis,test_val_LDA_predictionsDis)
get_auc_mean_sd(test_LDA_12mo,test_val_LDA_predictions12mo)
# 
get_auc_mean_sd(self_kNN_dis,self_val_kNN_predictionsDis)
get_auc_mean_sd(self_kNN_12mo,self_val_kNN_predictions12mo)
get_auc_mean_sd(test_kNN_dis,test_val_kNN_predictionsDis)
get_auc_mean_sd(test_kNN_12mo,test_val_kNN_predictions12mo)
```
   