train_GLM<-function(train_CV,Y,currTrainIdx,a,k){
    tempList<-lapply(train_CV, function(x) cv.glmnet(data.matrix(x),Y[currTrainIdx],alpha = a,family = "binomial",type.measure ="auc",nfolds=k))
    names(tempList)<-c(
        "bp_clin_glm",
        "fe_clin_glm",
        "fp_clin_glm",
        "mf_clin_glm",
        "sm_clin_glm",
        "wv_clin_glm",
        "clin_only_glm",
        "bp_only_glm",
        "fe_only_glm",
        "fp_only_glm",
        "mf_only_glm",
        "sm_only_glm",
        "wv_only_glm"
    )
    return(tempList)
} 