---
title: "Dimensionality Reduction of Motion Features with Linear Optimal Low Rank Projection (LOL)"
author: "Shubhayu Bhattacharyay and Matthew Wang"
date: "4/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(devtools)
if (!require(lolR)) install_github('neurodata/lol', build_vignettes=TRUE, force=TRUE)
library(lolR)
library(R.matlab)
library(tidyverse)
library(ggplot2)
library(plotly)
library(naniar)
if(!exists("sensors")) {
  sensors<-readMat('../motion_feature_data/imputed_complete_sensor_data.mat')$sensors
}

na_strings <- c("NA", "N A", "N / A", "N/A", "N/ A", "Not Available", "NOt available","NaN")

if(!exists("patient_table")) {
  patient_table<-read.csv('../clinical_data/patient_table.csv',na.strings=c("NA","NaN", " ") )%>%replace_with_na_all(condition = ~.x %in% na_strings)%>%mutate(GOSE=factor(GOSE),GOSE_1yr=factor(GOSE_1yr),Death=factor(Death),Death_1yr=factor(Death_1yr))
}
studyPatients<-c(2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,58,59,60,61,62,63,64,66,67)
studyPatientsPY<-c(2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,49,51,46,47,48,50,52,53,54,55,56,57,59,60,61,62,63,64,65,67,68)
```

## Resolve mismatch between accelerometry and clinical data

```{r}
sortOrder<-sort(studyPatientsPY,index.return=TRUE)$ix
PYpatient_table<-patient_table[sortOrder,]

PY_1yr_patient_table<-PYpatient_table %>% drop_na(Death_1yr)
```

## Organize `sensors` data

```{r}
temp_var<-do.call(rbind,sensors)

band_powerFeats<-do.call(cbind,temp_var[1:7])
freq_entropyFeats<-do.call(cbind,temp_var[8:14])
freq_pairsFeats<-do.call(cbind,temp_var[15:28])
med_freqFeats<-do.call(cbind,temp_var[29:35])
smaFeats<-do.call(cbind,temp_var[36:42])
waveletsFeats<-do.call(cbind,temp_var[43:49])
```

## Run Linear Optimal Low Rank Projection

```{r}
r<-5
Y<-PYpatient_table$GOSE
band_powerLOL_GOSE <- lol.project.lol(band_powerFeats, Y, r)
freq_entropyLOL_GOSE <- lol.project.lol(freq_entropyFeats, Y, r)
freq_pairsLOL_GOSE <- lol.project.lol(freq_pairsFeats, Y, r)
med_freqLOL_GOSE <- lol.project.lol(med_freqFeats, Y, r)
smaLOL_GOSE <- lol.project.lol(smaFeats, Y, r)
waveletsLOL_GOSE <- lol.project.lol(waveletsFeats, Y, r)

r<-5
Y<-PYpatient_table$GOSE_1yr
band_powerLOL_GOSE_1yr <- lol.project.lol(band_powerFeats[!is.na(Y),], Y[!is.na(Y)], r)
freq_entropyLOL_GOSE_1yr <- lol.project.lol(freq_entropyFeats[!is.na(Y),], Y[!is.na(Y)], r)
freq_pairsLOL_GOSE_1yr <- lol.project.lol(freq_pairsFeats[!is.na(Y),], Y[!is.na(Y)], r)
med_freqLOL_GOSE_1yr <- lol.project.lol(med_freqFeats[!is.na(Y),], Y[!is.na(Y)], r)
smaLOL_GOSE_1yr <- lol.project.lol(smaFeats[!is.na(Y),], Y[!is.na(Y)], r)
waveletsLOL_GOSE_1yr <- lol.project.lol(waveletsFeats[!is.na(Y),], Y[!is.na(Y)], r)

r<-5
Y<-PYpatient_table$Death
band_powerLOL_Death <- lol.project.lol(band_powerFeats, Y, r)
freq_entropyLOL_Death <- lol.project.lol(freq_entropyFeats, Y, r)
freq_pairsLOL_Death <- lol.project.lol(freq_pairsFeats, Y, r)
med_freqLOL_Death <- lol.project.lol(med_freqFeats, Y, r)
smaLOL_Death <- lol.project.lol(smaFeats, Y, r)
waveletsLOL_Death <- lol.project.lol(waveletsFeats, Y, r)

r<-5
Y<-PYpatient_table$Death_1yr
band_powerLOL_Death_1yr <- lol.project.lol(band_powerFeats[!is.na(Y),], Y[!is.na(Y)], r)
freq_entropyLOL_Death_1yr <- lol.project.lol(freq_entropyFeats[!is.na(Y),], Y[!is.na(Y)], r)
freq_pairsLOL_Death_1yr <- lol.project.lol(freq_pairsFeats[!is.na(Y),], Y[!is.na(Y)], r)
med_freqLOL_Death_1yr <- lol.project.lol(med_freqFeats[!is.na(Y),], Y[!is.na(Y)], r)
smaLOL_Death_1yr <- lol.project.lol(smaFeats[!is.na(Y),], Y[!is.na(Y)], r)
waveletsLOL_Death_1yr <- lol.project.lol(waveletsFeats[!is.na(Y),], Y[!is.na(Y)], r)
```

## Visualize LOL projections

```{r}

data <- data.frame(x1=band_powerLOL_GOSE$Xr[,1], x2=band_powerLOL_GOSE$Xr[,2],x3=band_powerLOL_GOSE$Xr[,3],y=PYpatient_table$GOSE)
viz<-ggplot(data, aes(x=x1, y=x2, color=y)) +
  geom_point() +
  xlab("x1") +
  ylab("x2") +
  ggtitle("Projected Data using LOL")

ggplotly(viz)

```


```{r}
plot_ly(x=data$x1, y=data$x2, z=data$x3, type="scatter3d", mode="markers", color=data$y)


```